---
- name: stop zookeeper
  sudo: yes
  command: bin/zkServer.sh stop
  args:
    chdir:  "{{zookeeper.symlink}}"
    removes: /var/lib/zookeeper/zookeeper_server.pid

- name: start zookeeper
  sudo: yes
  command: bin/zkServer.sh start
  args:
    chdir:   "{{zookeeper.symlink}}"
    creates: /var/lib/zookeeper/zookeeper_server.pid
  register: zookeeper_start_results
  failed_when: "'FAILED' in zookeeper_start_results.stderr"