--- 
- name: Prepare basic env for php apps on all nodes
  hosts: all
  remote_user: vagrant
  connection: local
  sudo: yes
  vars_files:
    - ../.project_name.yml
  roles:
    - zookeeper
    - kafka

